// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UserController is an autogenerated mock type for the UserController type
type UserController struct {
	mock.Mock
}

// Login provides a mock function with given fields: c
func (_m *UserController) Login(c *gin.Context) {
	_m.Called(c)
}

// PromoteUser provides a mock function with given fields: c
func (_m *UserController) PromoteUser(c *gin.Context) {
	_m.Called(c)
}

// Signup provides a mock function with given fields: c
func (_m *UserController) Signup(c *gin.Context) {
	_m.Called(c)
}

type mockConstructorTestingTNewUserController interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserController creates a new instance of UserController. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserController(t mockConstructorTestingTNewUserController) *UserController {
	mock := &UserController{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
